// lib/donors/parse-scan-input.ts
//
// A scan can arrive two ways, and both have to resolve to the same id:
//   - The camera (BarcodeDetector) decodes the QR's actual payload, the full
//     Check in URL: https://furnitureassist.com/in-kind-checkin/
//     in-kind-checkin.html?id=recXXXXXXXXXXXXXX&donorName=...
//   - The Bluetooth HID scanner types whatever the same QR encodes and
//     presses Enter — normally the identical URL, but also used for manual
//     entry / testing with a bare record id typed directly.
//
// donorName is never read here. It's generated by the Check in URL formula
// from First/Last Name, not a stored field — display-only, per the branch
// brief. The write only ever trusts `id`.
//
// Authoritative here, not just in the phone page's own client-side handling
// — never trust a client-side extraction alone for what gets written.

import { REC_ID_RE } from '@/lib/airtable/client'

/** Returns a validated recXXXXXXXXXXXXXX, or null if nothing usable was found. */
export function parseScanInput(raw: string): string | null {
  const input = raw.trim()
  if (!input) return null

  // Bare id, typed or scanned directly.
  if (REC_ID_RE.test(input)) return input

  // Full URL — pull `id` out of the query string. Tolerant of the value
  // arriving with or without a scheme, since a scanner or a pasted test
  // value might omit it.
  try {
    const url = new URL(input.includes('://') ? input : `https://${input}`)
    const id = url.searchParams.get('id')
    if (id && REC_ID_RE.test(id)) return id
  } catch {
    // Not a parseable URL and not a bare id — fall through to null.
  }

  return null
}
